version: 0.0
os: linux

files:
  - source: /server
    destination: /home/ubuntu/app/server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: server/script/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: server/script/start.sh
      timeout: 60
      runas: ubuntu
