version: 0.0
os: linux

files:
  - source: /server
    destination: /home/ubuntu/app/server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart: 
    - location: server/script/deploy.sh
      timeout: 60 
      runas: ubuntu
