spring:
  main:
    allow-bean-definition-overriding: true

  datasource: # MySQL DB 설정
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.127.80:3306/GENE10S
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      platform: mysql
  jpa: # JPA 설정
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false

  session:
    redis:
      flush-mode: on_save
      namespace: "gene10s:session:airport"

  data:
    redis:
      host: 43.203.119.163
      port: 6379
      password: ${REDIS_PASSWORD}
      repositories:
        enabled: false

server:
  url: https://api.reservation.genesis-airport.com
  servlet:
    session:
      cookie:
        name: SID
        domain: genesis-airport.com
        path: /
        http-only: true
        secure: true
