name: Deploy Frontend-user to S3

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'client/**' 

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: reservation.genesis-airport.com

permissions:
  contents: read

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: .env setting
        run: |
          echo "REACT_APP_REDIRECT_URI_CLIENT=${{ secrets.REACT_APP_REDIRECT_URI_CLIENT }}" >> .env
          echo "REACT_APP_CLIENT_ID=${{ secrets.REACT_APP_CLIENT_ID }}" >> .env
          echo "REACT_APP_CLIENT_SECRET=${{ secrets.REACT_APP_CLIENT_SECRET }}" >> .env
          echo "REACT_APP_SERVER_URL=${{ secrets.REACT_APP_SERVER_URL }}" >> .env
        working-directory: ./client

      - name: Build React app
        run: npm run build
        working-directory: ./client

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload to AWS S3
        run: aws s3 sync ./client/build/ s3://$S3_BUCKET_NAME/ --delete
