name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

#리전, 버킷 이름, CodeDeploy앱 이름, CodeDeploy배포 그룹 이름
env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: genesis-airport-deploy
  CODE_DEPLOY_APPLICATION_NAME: genesis-airport-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: genesis-airport-codedeploy-deployment-group

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    # (1)기본 체크아웃
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # (2) JDK 17세팅
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # not executable 에러 방지를 위한 권한 부여
    - name: Run chmod to make gradlew executable
      run: chmod +x gradlew
      working-directory: ./server
      
    # (3) Gradle build
    - name: Build with Gradle without tests
      run: ./gradlew build -x test
      working-directory: ./server


    # (4) AWS인증 (IAM사용자, Access Key, Secret Key)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # (5)빌드 결과물을 S3버킷에 업로드
    - name: Upload to AWS S3
      run: |
          aws deploy push \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --ignore-hidden-files \
            --s3-location s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip \
            --source server/


    # (6) S3버킷에 있는 파일을 대상으로 CodeDeploy실행
    - name: Deploy to AWS EC2 from S3
      run: |
          aws deploy create-deployment \\
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \\
            --deployment-config-name CodeDeployDefault.AllAtOnce \\
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \\
            --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip
